# Welcome to Jekyll!
#

# Site settings
title: International Submarine Races
description: |
  University of Miami    
  American Society of Mechanical Engineers
owner: UMiami ASME # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: hurricane.asme@gmail.com
baseurl: "/ISR" # the subpath of your site, e.g. /blog
url: "https://umiamiasme.github.io" # the base hostname & protocol for your site
social:
  #twitter: https://twitter.com/<username>
  github: https://github.com/UMiamiASME/
  undo: https://orgsync.com/55150/chapter/
  facebook-official: https://facebook.com/UMASME/
  #google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
